upstars-global/cardona-core-service

src/components/TextEditorWysiwyg/index.vue
=> BAC-3228: fix path to file on insert image

src/@fake-db/demo/index.ts, src/assets/styles/components/vue-select.scss, src/components/templates/FieldGenerator/_components/SelectField.vue
Create new pull request by github
=> Bac 3139 selector core

src/@model/group.ts, src/plugins/i18n/locales/en.json
Change localization keys and order field in sidebar group
=> BAC-3291: fix localization

src/assets/styles/components/v-switch.scss
Add global style on disabled state to component VSwicth
=> BAC-3296: add global style to  switch on disable

src/helpers/base-permissions.ts
Fix base permission for local key permission
=> BAC-3079: fix base permission for local key permission

src/components/CountriesSelect.vue, src/plugins/i18n/locales/en.json
https://upstars.atlassian.net/browse/BAC-3357
=> BAC-3357_countries-placeholder-core

src/@model/templates/baseList.ts, src/components/templates/BaseList/_components/fields/ItemActions.vue, src/components/templates/BaseList/index.vue
https://upstars.atlassian.net/browse/BAC-3355
=> BAC-3355_list-actions-core

src/components/FiltersBlock/filters.ts
Add actual fetch options action name for filter item of banner strategy
=> BAC-3439: fix fetchOptionsActionName  for banner strategy filter

src/components/CTable/index.vue
https://upstars.atlassian.net/browse/BAC-3395
=> BAC-3395_balance-log-new-fields-core

src/@core/components/app-form-elements/AppTextField.vue, src/components/templates/FieldGenerator/_components/TextField.vue
https://upstars.atlassian.net/browse/BAC-3485
=> BAC-3485_fix-banner-bg-field-core

src/components/CountriesSelect.vue
https://upstars.atlassian.net/browse/BAC-3402
=> BAC-3402_countries-sort-core

src/components/FiltersBlock/index.vue
https://upstars.atlassian.net/browse/BAC-3391
=> BAC-3391_filters-label-case-core

src/components/templates/SideBar/index.vue
https://upstars.atlassian.net/browse/BAC-3505
=> BAC-3505_balance-history-sidebar-styles-core

src/@model/templates/baseField/base.ts, src/@model/templates/baseField/select.ts, src/components/templates/FieldGenerator/_components/MultiSelectField.vue, src/components/templates/FieldGenerator/_components/SelectField.vue
https://upstars.atlassian.net/browse/BAC-3499
=> BAC-3499_select-position-cb-core

src/components/DynamicFieldList.vue
https://upstars.atlassian.net/browse/BAC-3501
=> BAC-3501_vip-manager-styles-core

src/@model/templates/baseList.ts, src/components/FiltersBlock/index.vue
https://upstars.atlassian.net/browse/BAC-3507
=> BAC-3507_filter-class-optional-core

src/components/templates/BaseList/_components/fields/CopyField.vue, src/components/templates/_components/CopyField.vue
=> BAC-3570_fix color icon

src/components/templates/_components/BtnIcon.vue, src/components/templates/_components/CopyField.vue, src/components/templates/_components/InnerBlankLink.vue, src/components/templates/_components/PhoneField.vue, src/components/templates/_components/StatementField.vue, src/components/templates/_components/StatusField.vue, src/components/templates/_components/StatusWithDateField.vue, src/components/templates/_components/SumAndCurrency.vue, src/components/templates/_components/SumPeriod.vue, src/components/templates/_components/TransactionType.vue, tests/unit/templates/_components/BadgeCopy.spec.ts, tests/unit/templates/_components/BtnIcon.spec.ts, tests/unit/templates/_components/CopyField.spec.ts, tests/unit/templates/_components/DateField.spec.ts, tests/unit/templates/_components/DateWithSecondsField.spec.ts, tests/unit/templates/_components/InnerBlankLink.spec.ts, tests/unit/templates/_components/PhoneField.spec.ts, tests/unit/templates/_components/StatementField.spec.ts, tests/unit/templates/_components/StatusField.spec.ts, tests/unit/templates/_components/StatusWithDateField.spec.ts, tests/unit/templates/_components/SumAndCurrency.spec.ts, tests/unit/templates/_components/SumPeriod.spec.ts, tests/unit/templates/_components/TransactionType.spec.ts, tests/unit/templates/shared-tests/copy-and-shortValue.ts, tests/unit/templates/shared-tests/sum-and-currency.ts, tests/unit/templates/shared-tests/test-case-generator.ts, tests/unit/utils.ts
Add general test case for unit tests
=> Bac 3537 refactor tests

components.d.ts, src/assets/styles/components/vue-select.scss, src/components/TextEditorWysiwyg/index.vue, src/components/templates/LocaleForm/index.vue
=> BAC-3615: fix color border of select

src/components/CTable/index.vue
https://upstars.atlassian.net/browse/BAC-3361
=> BAC-3361_fix-skeleton-rows-core

src/components/templates/BaseList/_components/MultipleActions.vue
https://upstars.atlassian.net/browse/BAC-3611
=> BAC-3611_archive-block-height-core

src/components/templates/ViewGenerator/index.vue, tests/unit/ViewGenerator/ViewGenerator.spec.ts, tests/unit/templates/shared-tests/test-case-generator.ts
Add unit tests for ViewGenerator/index.vue for all props and cases
=> Bac 3774 test main view genreator

src/components/templates/BaseList/index.vue
Change empty state of BaseList
=> BAC-3535: fix empty state of empty list

src/assets/styles/styles.scss
Remove animation from tabs in global
=> BAC-3736: remove animation from tabs (global)

src/@core/components/app-form-elements/AppTextField.vue, src/components/templates/BaseList/_components/fields/ItemActions.vue, src/components/templates/BaseList/index.vue
https://upstars.atlassian.net/browse/BAC-2963
=> BAC-2963_tournament-participants-core

src/@model/validations.ts
https://upstars.atlassian.net/browse/BAC-3755
=> BAC-3755_templates-time-validation-core

src/@model/enums/icons.ts, src/components/FiltersBlock/index.vue
https://upstars.atlassian.net/browse/BAC-3830
=> BAC-3830_miles-list-core

src/services/api/index.ts
https://upstars.atlassian.net/browse/BAC-4018
=> BAC-4018: Hot fix retry api

src/components/templates/BaseList/index.vue
https://upstars.atlassian.net/browse/BAC-3898
=> BAC-3898_currency-history-scroll-core

src/components/permitionsForm/GroupFragmentSettingsTables.vue, src/layouts/components/AppBreadcrumb.vue
https://upstars.atlassian.net/browse/BAC-3802
=> BAC-3802_breadcrumbs-styles-core

src/@model/validations.ts, src/components/templates/FieldGenerator/index.vue, tests/unit/templates/FieldGenerator/ConditionsField.spec.ts, tests/unit/templates/FieldGenerator/FieldGenerator.spec.ts, yarn.lock
https://upstars.atlassian.net/browse/BAC-3758
=> BAC-3758_error-label-case-core

src/@model/templates/baseField/base.ts, src/components/templates/FieldGenerator/_components/MultiSelectField.vue, src/components/templates/FieldGenerator/_components/SelectField.vue
https://upstars.atlassian.net/browse/BAC-4325
=> BAC-4325_fix-gift-search-core

src/components/templates/BaseList/index.vue
Повтор реализации https://upstars.atlassian.net/browse/BAC-4145, но для кора.
=> BAC-4263 close others on edit [core]

src/components/templates/FieldGenerator/index.vue
https://upstars.atlassian.net/browse/BAC-4433
=> BAC-4433_notification-field-type-core

src/@model/templates/baseField/base.ts, src/components/templates/FieldGenerator/_components/MultiSelectField.vue, src/components/templates/FieldGenerator/_components/SelectField.vue, src/helpers/infiniteScroll.ts, src/plugins/i18n/locales/en.json, vitest.setup.ts
Добавлен функционал подзагрузки элементов по 50 в селектах при скроле.
=> BAC-2088 select/multiselect infinite load

src/@model/enums/icons.ts
https://upstars.atlassian.net/browse/BAC-4346
=> BAC-4346_achievements-list-core

src/@model/templates/baseList.ts, src/@model/templates/baseSection.ts
https://upstars.atlassian.net/browse/BAC-4348
=> BAC-4348_improve-types-core

src/@model/enums/modal.ts, src/components/CountriesSelect.vue, src/plugins/i18n/locales/en.json
https://upstars.atlassian.net/browse/BAC-4728
=> BAC-4728_remove-all-countries-core

src/components/templates/BaseSection/index.vue
https://upstars.atlassian.net/browse/BAC-4802
=> BAC-4802_fix-save-and-exit-core

src/@model/router.ts, src/helpers/router.ts
https://upstars.atlassian.net/browse/BAC-4833
=> BAC-4833_fix-url-core

src/components/templates/FieldGenerator/_components/DateField.vue
https://upstars.atlassian.net/browse/BAC-4865
=> BAC-4865_fix-edit-date-core

src/services/api/config.ts, src/services/api/index.ts
https://upstars.atlassian.net/browse/BAC-4665
=> BAC-4665_cache-dictionary-core

src/@model/templates/baseField/base.ts, src/@model/templates/baseList.ts, src/@model/templates/baseSection.ts, src/components/templates/BaseList/_components/ListSearch.vue, src/components/templates/BaseList/_components/fields/ItemActions.vue, src/components/templates/BaseList/index.vue, src/components/templates/BaseSection/index.vue, src/components/templates/FieldGenerator/index.vue, tests/unit/components/templates/BaseList/BaseList.spec.ts, tests/unit/components/templates/BaseList/_components/ItemActions.spec.ts
https://upstars.atlassian.net/browse/BAC-4749
=> BAC-4749_slots-types-core

src/@fake-db/demo/index.ts, src/@model/index.ts, src/@model/templates/baseField/base.ts, src/components/templates/BaseList/index.vue, src/store/modules/baseStoreCore.ts, src/store/modules/compostelaCore.ts, src/store/modules/demo.ts, src/store/modules/users.ts, tests/unit/components/templates/BaseList/BaseList.spec.ts
BREAKING CHANGE: Изменена структура payload для fetchEntityList
=> BAC-4499 Typed Request Payload [list, options]

src/components/templates/BaseList/index.vue
https://upstars.atlassian.net/browse/BAC-5161
=> BAC-5161_cohort-activation-core

src/store/modules/authCore.ts
https://upstars.atlassian.net/browse/BAC-4493
=> BAC-4493_google-auth-core

src/store/modules/appConfigCore.ts
https://upstars.atlassian.net/browse/BAC-5401
=> BAC-5401: Fix currency all project

src/@core/components/app-form-elements/AppDateTimePicker.vue, src/@model/templates/baseField/date.ts
https://upstars.atlassian.net/browse/BAC-5202
=> BAC-5202_fix-custom-period-core

src/@model/changePassword.ts, src/components/change-password/ChangePassword.vue
https://upstars.atlassian.net/browse/BAC-5454
=> BAC-5454: Fix password

src/components/templates/BaseList/index.vue
https://upstars.atlassian.net/browse/BAC-5385
=> BAC-5385_bot-activation-core

package.json, src/components/templates/BaseList/index.vue
https://upstars.atlassian.net/browse/BAC-5397
=> BAC-5397_improve-bonus-offer-core

src/components/templates/_components/InnerBlankLink.vue
https://upstars.atlassian.net/browse/BAC-5883
=> BAC-5883_fin-managers-sidebar-core2

src/helpers/amount.ts
https://upstars.atlassian.net/browse/BAC-6013
=> BAC-6013_number-format-core

src/helpers/audioCache.ts
https://upstars.atlassian.net/browse/BAC-5720
=> BAC-5720_cache-audio-core
